version: '3.3'
services:
  gateway:
    image: nginx:latest
    depends_on:
      - inference-service
    volumes:
      - ./gateway_nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"

  inference-service:
    build: ../../
    image: inference-service:latest
    command: sh src/startup.sh
    environment:
      - APP_MODULE=serve_model
      - PROMETHEUS_MULTIPROC_DIR=/tmp/prometheus

  scraping-controller:
    build:
      context: ../../
      dockerfile: src/scraper/controller/Dockerfile
    image: scraping-controller:latest
    command: sh src/startup.sh
    environment:
      - APP_MODULE=scraper.controller.controller
      - PROMETHEUS_MULTIPROC_DIR=/tmp/prometheus
#      - SCRAPE_START_TIMESTAMP=
#      - SCRAPE_INCREMENT_SECONDS=
      - API_KEYS=thisisanapikey
      - LOG_LEVEL=DEBUG

  scraping-service:
    build:
      context: ../../
      dockerfile: src/scraper/app/Dockerfile
    image: scraping-service:latest
    command: src/startup.sh
    environment:
      - APP_MODULE=scraper.app.scraper
      - CONTROLLER_HOST=http://scraping-controller:5000
      - SCRAPE_SAVE_DIR=/root/data/
      - DATA_DIR=/root/data/raw/
      - PROMETHEUS_MULTIPROC_DIR=/tmp/prometheus
      - LOG_LEVEL=DEBUG
    volumes:
      - ../../data/:/root/data/
