name: Check commit format

on: [push]

jobs:
  build:
    # Do not run commit check on merge commits
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install commitizen
      run: |
        python -m pip install --upgrade pip
        pip install "$(grep commitizen requirements.txt)"
    - name: Run commitizen check
      run: |
        cz check --rev-range origin/main..HEAD
